name: electra
description: A new Flutter project.

# Prevent the package from being published to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10
  cupertino_icons: ^1.0.6
  percent_indicator: ^4.2.4
  intl: ^0.20.2
  shared_preferences: ^2.2.3
  http: ^1.2.2
  supabase_flutter: ^2.8.3
  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

assets:
    - assets/images/logo.jpg  # Add specific assets
    - assets/images/          # Include the entire folder

fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto_condensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto_Condensed-Regular.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700